### ISSUE TITLE
about drug code mapping files

### ISSUE THREAD

**Issue by liuxiaohao-xn** [sjy1203/GAMENet#12]
Thank you very much for the code!
Regarding the data source, I am a bit confused. [Drug code mapping files] already exists under the [data] directory. Can the source of these data be provided?

**Comment by sjy1203** [comment]
1. drug-atc.csv can be found at http://sideeffects.embl.de/download/

2. ndc2atc_level4.csv can be got using https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html#uLink=RxNorm_REST_findRxcuiById

3. drug-DDI.csv can be found at http://snap.stanford.edu/biodata/datasets/10017/10017-ChChSe-Decagon.html

**Comment by liuxiaohao-xn** [comment]
> 1. drug-atc.csv can be found at http://sideeffects.embl.de/download/
> 2. ndc2atc_level4.csv can be got using https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html#uLink=RxNorm_REST_findRxcuiById
> 3. drug-DDI.csv can be found at http://snap.stanford.edu/biodata/datasets/10017/10017-ChChSe-Decagon.html

Thank you for sharing and wish you good
